[package]
name = "mlir-sys"
version = "230.0.0"
authors = ["McCoy R. Becker", "Yota Toyama", "Edgar Luque"]
keywords = ["llvm", "mlir"]
categories = ["external-ffi-bindings"]
edition = "2024"
description = "Rust bindings to the MLIR C API."
repository = "https://github.com/mlir-rs/mlir-sys"
readme = "README.md"
links = "MLIR"
license-file = "LICENSE"

[build-dependencies]
bindgen = "0.72.1"

[features]
no-version-check = []
